### ISSUE TITLE
make things embed-friendly

### ISSUE THREAD

**Issue by xlotlu** [EEA-Norway-Grants/dataviz#233]
Catch-all for embed issues

##### Styling-related:
- [x] scope all component styles under a root-level selector. related to #385.
- [x] position absolute on dropdowns breaks things. solve along with #227.
- [x] icons are 404, because of img src. they need to be specified with css classes, or set with svg use. (or really, both). fix along with #69.

##### Code-related:
- [x] there is no way to specify props per-component. related to #231.
- [x] header code is dangerous for remote, see #235.

##### Configuration issues:
- [x] ( #pre-production ) if caching json output from api, nginx needs to take care of CORS. same goes for non-api json assets.
